# Generated by Django 5.2.4 on 2025-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='company_logo',
            field=models.URLField(blank=True, help_text='URL to company logo (optional)'),
        ),
    ]
